RSS Виртуальная клавиатура
IAleks94/virtual-keyboard pull request #1
Opened 2020-04-05 10:21 UTC by IAleks94

1. задание - https://github.com/rolling-scopes-school/tasks/blob/master/tasks/codejam-virtual-keyboard.md
2. скриншот -![image](https://user-images.githubusercontent.com/57172661/78472059-aea5ca80-773e-11ea-8cc8-0d6fe6221400.png)
3. демо -https://ialeks94.github.io/virtual-keyboard/
4. дата сдачи: 2020-04-05 / дата дедлайна: 07.04.2020;
5. Оценка 110: (Еее я сделал все, вроде) :
### Минимальный набор +30
* Реализована генерация DOM-элементов и тела в index.html пустой изначально (может находиться только тег script) +20
* Нажатие на кнопку на физической клавиатуре подсвечивает кнопку на виртуальной странице -влево вправо) +10
### Стандартный набор +30 
* Переключение между русским и английским языком (сочетание клавиш для переключения языка должно быть указано на странице с клавиатурой); +15
* Клавиши мышки на виртуальной клавиатуре или кнопки на клавиатуре, текстовые символы в текстовом поле (текстовая область) +15
### Дополнительный набор +15
* Реализована анимация на кнопке +15
### Технические требования +35 
* использование в коде фишек стандарта ES6 и выше (classes, деструктуризация и т.д.): +15
* использование eslint: +10
* требования к репозиторию, коммитам и PR выполнены: +10

###штрафы: (-15) (ну я от ошибок избавился так что должно вроде без штрафа)
 * ошибки в консоли, связанные с исполняемым кодом(ошибки типа favicon.ico: Failed to load resource: the server responded with a status of 404 не учитываются) или предупреждения eslint-config-airbnb-base: -15

2020-04-07 18:50 UTC, dzmitry-kavalenka requested changes
rewrite `createKeyBoard` func to remove nested for loops.
you can use find and forEach methods instead.

2020-04-07 18:50 UTC, Heat98 commented on script.js
>      ['ё', '1', '2', '3', '4', '5', '6', '7', '8', '9', '0', '-', '=', 'Backspace'],
create constants with the same buttons and spread it
* e.g ```const numbers = ['1', '2', '3', '4', '5', '6', '7', '8', '9', '0'];```
and then ```keyArrRu: ['ё', ...numbers, '-', '=', 'Backspace'];```

2020-04-07 18:50 UTC, Heat98 commented on script.js
>  body.append(input);
create separate function for it

2020-04-07 18:50 UTC, Heat98 commented on script.js
>  let board;
is it necessary to be a global value?

2020-04-07 19:53 UTC, dzmitry-kavalenka approved these changes

2020-04-07 20:05 UTC, IAleks94 commented on script.js
>  body.append(input);
input creating function ?

2020-04-11 10:14 UTC, Heat98 commented on script.js
>  body.append(input);
all of this code

2020-04-13 11:07 UTC, IAleks94 commented
like I fixed it

2020-04-13 11:07 UTC, merged